# Generated by Django 4.1.7 on 2023-03-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_tecrec_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecrec_data",
            name="name",
            field=models.CharField(default=" ", max_length=30),
        ),
    ]
